-- base.lua
-- Base editor and syntax highlighting groups
local colors = require("elixir-bloom.colors")
local M = {}
function M.setup()
	local base = {
		Normal = { fg = colors.elixir15, bg = colors.elixir0 },
		NormalNC = { fg = colors.elixir15, bg = colors.elixir0 },
		NormalFloat = { fg = colors.elixir15, bg = colors.elixir1 },
		FloatBorder = { fg = colors.elixir9 },
		FloatTitle = { fg = colors.elixir7 },
		ColorColumn = { bg = colors.elixir2 },
		Cursor = { fg = colors.elixir0, bg = colors.elixir15 },
		CursorLine = { bg = colors.elixir2 },
		CursorLineNr = { fg = colors.elixir7, bold = true },
		LineNr = { fg = colors.elixir3 },
		Directory = { fg = colors.elixir7 },
		ErrorMsg = { fg = colors.elixir11 },
		WarningMsg = { fg = colors.elixir12 },
		MoreMsg = { fg = colors.elixir14 },
		Question = { fg = colors.elixir14 },
		Search = { bg = colors.elixir3 },
		IncSearch = { bg = colors.elixir3, bold = true },
		Substitute = { bg = colors.elixir3, bold = true },
		MatchParen = { fg = colors.elixir7, bold = true },
		NonText = { fg = colors.elixir9 },
		Whitespace = { fg = colors.elixir9 },
		SpecialKey = { fg = colors.elixir3 },
		Pmenu = { fg = colors.elixir15, bg = colors.elixir1 },
		PmenuSel = { fg = colors.elixir15, bg = colors.elixir2 },
		PmenuSbar = { bg = colors.elixir1 },
		PmenuThumb = { bg = colors.elixir2 },
		Visual = { bg = colors.elixir3 },
		VisualNOS = { bg = colors.elixir3 },
		SignColumn = { fg = colors.elixir15, bg = colors.elixir0 },
		WildMenu = { fg = colors.elixir15, bg = colors.elixir2 },
		Comment = { fg = colors.elixir3, italic = true },
		Constant = { fg = colors.elixir7 },
		String = { fg = colors.elixir7 },
		Character = { fg = colors.elixir14 },
		Number = { fg = colors.elixir13 },
		Boolean = { fg = colors.elixir13 },
		Float = { fg = colors.elixir13 },
		Identifier = { fg = colors.elixir6 },
		Function = { fg = colors.elixir7 },
		Statement = { fg = colors.elixir7 },
		Conditional = { fg = colors.elixir7 },
		Repeat = { fg = colors.elixir7 },
		Label = { fg = colors.elixir7 },
		Operator = { fg = colors.elixir15 },
		Keyword = { fg = colors.elixir7 },
		Exception = { fg = colors.elixir7 },
		PreProc = { fg = colors.elixir10 },
		Include = { fg = colors.elixir7 },
		Define = { fg = colors.elixir7 },
		Macro = { fg = colors.elixir10 },
		PreCondit = { fg = colors.elixir10 },
		Type = { fg = colors.elixir14 },
		StorageClass = { fg = colors.elixir7 },
		Structure = { fg = colors.elixir14 },
		Typedef = { fg = colors.elixir14 },
		Special = { fg = colors.elixir8 },
		SpecialChar = { fg = colors.elixir8 },
		Tag = { fg = colors.elixir7 },
		Delimiter = { fg = colors.elixir9 },
		SpecialComment = { fg = colors.elixir9 },
		Debug = { fg = colors.elixir12 },
		DiffAdd = { fg = colors.elixir14, bg = colors.elixir0 },
		DiffChange = { fg = colors.elixir13, bg = colors.elixir0 },
		DiffDelete = { fg = colors.elixir11, bg = colors.elixir0 },
		DiffText = { fg = colors.elixir7, bg = colors.elixir0 },
		Folded = { fg = colors.elixir3, bg = colors.elixir2 },
		FoldColumn = { fg = colors.elixir3, bg = colors.elixir0 },
		SpellBad = { undercurl = true, sp = colors.elixir11 },
		SpellCap = { undercurl = true, sp = colors.elixir13 },
		SpellLocal = { undercurl = true, sp = colors.elixir14 },
		SpellRare = { undercurl = true, sp = colors.elixir10 },
		Title = { fg = colors.elixir7, bold = true },
		ModeMsg = { fg = colors.elixir15, bold = true },
		MsgArea = { fg = colors.elixir15 },
		MsgSeparator = { fg = colors.elixir9 },
		TabLine = { fg = colors.elixir3, bg = colors.elixir1 },
		TabLineFill = { bg = colors.elixir1 },
		TabLineSel = { fg = colors.elixir7, bg = colors.elixir0, bold = true },
		StatusLine = { fg = colors.elixir15, bg = colors.elixir1 },
		StatusLineNC = { fg = colors.elixir4, bg = colors.elixir1 },
		VertSplit = { fg = colors.elixir2, bg = colors.elixir1 },
	}
	return base
end
return M
