-- Base editor and syntax highlighting groups
local colors = require("elixir-bloom.colors")
local M = {}

function M.setup()
	local base = {
		Normal = { fg = colors.white, bg = colors.bg },
		NormalNC = { fg = colors.white, bg = colors.bg },
		NormalFloat = { fg = colors.white, bg = colors.bg_dark },
		FloatBorder = { fg = colors.cyan },
		FloatTitle = { fg = colors.blue },
		ColorColumn = { bg = colors.bg2 },
		Cursor = { fg = colors.bg, bg = colors.white },
		CursorLine = { bg = colors.bg_highlight },
		CursorLineNr = { fg = colors.blue, bold = true },
		LineNr = { fg = colors.b_black },
		Directory = { fg = colors.blue },
		ErrorMsg = { fg = colors.cherry3 },
		WarningMsg = { fg = colors.cherry2 },
		MoreMsg = { fg = colors.green },
		Question = { fg = colors.green },
		Search = { bg = colors.bg_visual },
		IncSearch = { bg = colors.bg_visual, bold = true },
		Substitute = { bg = colors.bg_visual, bold = true },
		MatchParen = { fg = colors.blue, bold = true },
		NonText = { fg = colors.cyan },
		Whitespace = { fg = colors.cyan },
		SpecialKey = { fg = colors.b_black },
		Pmenu = { fg = colors.white, bg = colors.bg_dark },
		PmenuSel = { fg = colors.white, bg = colors.bg2 },
		PmenuSbar = { bg = colors.bg_dark },
		PmenuThumb = { bg = colors.bg2 },
		Visual = { bg = colors.bg3 },
		VisualNOS = { bg = colors.bg_visual },
		SignColumn = { fg = colors.white, bg = colors.bg },
		WildMenu = { fg = colors.white, bg = colors.bg2 },

		Comment = { fg = colors.b_black, italic = true },
		Constant = { fg = colors.blue },
		String = { fg = colors.blue },
		Character = { fg = colors.green },
		Number = { fg = colors.yellow },
		Boolean = { fg = colors.yellow },
		Float = { fg = colors.yellow },
		Identifier = { fg = colors.b_yellow },
		Function = { fg = colors.blue },
		Statement = { fg = colors.blue },
		Conditional = { fg = colors.blue },
		Repeat = { fg = colors.blue },
		Label = { fg = colors.blue },
		Operator = { fg = colors.white },
		Keyword = { fg = colors.blue },
		Exception = { fg = colors.blue },
		PreProc = { fg = colors.magenta },
		Include = { fg = colors.blue },
		Define = { fg = colors.blue },
		Macro = { fg = colors.magenta },
		PreCondit = { fg = colors.magenta },
		Type = { fg = colors.b_green },
		StorageClass = { fg = colors.blue },
		Structure = { fg = colors.b_green },
		Typedef = { fg = colors.b_green },
		Special = { fg = colors.b_blue },
		SpecialChar = { fg = colors.b_blue },
		Tag = { fg = colors.blue },
		Delimiter = { fg = colors.b_cyan },
		SpecialComment = { fg = colors.cyan },
		Debug = { fg = colors.cherry2 },

		DiffAdd = { fg = colors.green, bg = colors.none },
		DiffChange = { fg = colors.yellow, bg = colors.none },
		DiffDelete = { fg = colors.cherry3, bg = colors.none },
		DiffText = { fg = colors.blue, bg = colors.none },

		Folded = { fg = colors.b_black, bg = colors.bg2 },
		FoldColumn = { fg = colors.b_black, bg = colors.bg },

		SpellBad = { undercurl = true, sp = colors.cherry3 },
		SpellCap = { undercurl = true, sp = colors.yellow },
		SpellLocal = { undercurl = true, sp = colors.green },
		SpellRare = { undercurl = true, sp = colors.magenta },

		Title = { fg = colors.blue, bold = true },
		ModeMsg = { fg = colors.white, bold = true },
		MsgArea = { fg = colors.white },
		MsgSeparator = { fg = colors.cyan },

		TabLine = { fg = colors.b_black, bg = colors.bg1 },
		TabLineFill = { bg = colors.bg1 },
		TabLineSel = { fg = colors.blue, bg = colors.bg0_h, bold = true },
		StatusLine = { fg = colors.white, bg = colors.bg_dark },
		StatusLineNC = { fg = colors.fg_dark, bg = colors.bg1 },
		VertSplit = { fg = colors.bg2, bg = colors.bg1 },
	}
	return base
end

return M
