-- final.lua
-- Setup for terminal colors and UI elements
local colors = require("elixir-bloom.colors")
local M = {}
function M.setup()
	local final = {
		terminal_color_0 = colors.elixir0,
		terminal_color_8 = colors.elixir3,
		terminal_color_1 = colors.elixir11,
		terminal_color_9 = colors.elixir12,
		terminal_color_2 = colors.elixir14,
		terminal_color_10 = colors.elixir14,
		terminal_color_3 = colors.elixir13,
		terminal_color_11 = colors.elixir6,
		terminal_color_4 = colors.elixir15,
		terminal_color_12 = colors.elixir8,
		terminal_color_5 = colors.elixir10,
		terminal_color_13 = colors.elixir8,
		terminal_color_6 = colors.elixir9,
		terminal_color_14 = colors.elixir9,
		terminal_color_7 = colors.elixir4,
		terminal_color_15 = colors.elixir15,
		SpellBad = { undercurl = true, sp = colors.elixir11 },
		SpellCap = { undercurl = true, sp = colors.elixir13 },
		SpellLocal = { undercurl = true, sp = colors.elixir14 },
		SpellRare = { undercurl = true, sp = colors.elixir3 },
		HealthError = { fg = colors.elixir11 },
		HealthWarning = { fg = colors.elixir12 },
		HealthSuccess = { fg = colors.elixir14 },
		WinBar = { fg = colors.elixir3, bg = colors.elixir0 },
		WinBarNC = { fg = colors.elixir3, bg = colors.elixir0 },
		WildMenu = { fg = colors.elixir15, bg = colors.elixir2 },
		QuickFixLine = { bg = colors.elixir2 },
		CurSearch = { link = "IncSearch" },
		MatchParen = { fg = colors.elixir9, bold = true },
		ModeMsg = { fg = colors.elixir15, bold = true },
		MsgArea = { fg = colors.elixir15 },
		MsgSeparator = { fg = colors.elixir9 },
		FloatBorder = { fg = colors.elixir9 },
		FloatTitle = { fg = colors.elixir9 },
		PmenuExtra = { fg = colors.elixir3, bg = colors.elixir1 },
		PmenuExtraSel = { fg = colors.elixir15, bg = colors.elixir2 },
		PmenuKind = { fg = colors.elixir6, bg = colors.elixir1 },
		PmenuKindSel = { fg = colors.elixir6, bg = colors.elixir2 },
		Whitespace = { fg = colors.elixir9 },
		NonText = { fg = colors.elixir9 },
		SpecialKey = { fg = colors.elixir3 },
		DapBreakpoint = { fg = colors.elixir11 },
		DapBreakpointCondition = { fg = colors.elixir13 },
		DapLogPoint = { fg = colors.elixir9 },
		DapStopped = { fg = colors.elixir14 },
		AerialClassIcon = { fg = colors.elixir14 },
		AerialConstructorIcon = { fg = colors.elixir9 },
		AerialEnumIcon = { fg = colors.elixir14 },
		AerialFunctionIcon = { fg = colors.elixir9 },
		AerialInterfaceIcon = { fg = colors.elixir14 },
		AerialMethodIcon = { fg = colors.elixir9 },
		AerialPackageIcon = { fg = colors.elixir6 },
		AerialPropertyIcon = { fg = colors.elixir6 },
		AerialVariableIcon = { fg = colors.elixir6 },
		NavicIconsFile = { fg = colors.elixir3 },
		NavicIconsModule = { fg = colors.elixir6 },
		NavicIconsNamespace = { fg = colors.elixir14 },
		NavicIconsPackage = { fg = colors.elixir6 },
		NavicIconsClass = { fg = colors.elixir14 },
		NavicIconsMethod = { fg = colors.elixir9 },
		NavicIconsProperty = { fg = colors.elixir6 },
		NavicIconsField = { fg = colors.elixir6 },
		NavicIconsConstructor = { fg = colors.elixir9 },
		NavicIconsEnum = { fg = colors.elixir14 },
		NavicIconsInterface = { fg = colors.elixir14 },
		NavicIconsFunction = { fg = colors.elixir9 },
		NavicIconsVariable = { fg = colors.elixir6 },
		NavicIconsConstant = { fg = colors.elixir9 },
		NavicIconsString = { fg = colors.elixir8 },
		NavicIconsNumber = { fg = colors.elixir13 },
		NavicIconsBoolean = { fg = colors.elixir13 },
		NavicIconsArray = { fg = colors.elixir14 },
		NavicIconsObject = { fg = colors.elixir14 },
		NavicIconsKey = { fg = colors.elixir12 },
		NavicIconsKeyword = { fg = colors.elixir9 },
		NavicIconsNull = { fg = colors.elixir11 },
		NavicIconsEnumMember = { fg = colors.elixir6 },
		NavicIconsStruct = { fg = colors.elixir14 },
		NavicIconsEvent = { fg = colors.elixir10 },
		NavicIconsOperator = { fg = colors.elixir15 },
		NavicIconsTypeParameter = { fg = colors.elixir14 },
		NavicText = { fg = colors.elixir15 },
		NavicSeparator = { fg = colors.elixir3 },
	}
	return final
end
return M
