-- treesitter.lua
-- Treesitter syntax highlighting configuration
local colors = require("elixir-bloom.colors")
local M = {}
function M.setup()
	local treesitter = {
		["@text"] = { fg = colors.elixir15 },
		["@text.strong"] = { fg = colors.elixir15, bold = true },
		["@text.emphasis"] = { fg = colors.elixir15, italic = true },
		["@text.underline"] = { underline = true },
		["@text.title"] = { fg = colors.elixir15, bold = true },
		["@text.literal"] = { fg = colors.elixir14 },
		["@text.uri"] = { fg = colors.elixir14, underline = true },
		["@comment"] = { fg = colors.elixir3, italic = true },
		["@comment.documentation"] = { fg = colors.elixir9 },
		["@comment.note"] = { fg = colors.elixir9 },
		["@comment.warning"] = { fg = colors.elixir11 },
		["@comment.error"] = { fg = colors.elixir11 },
		["@comment.todo"] = { fg = colors.elixir7, bold = true },
		["@punctuation.delimiter"] = { fg = colors.elixir12 },
		["@punctuation.bracket"] = { fg = colors.elixir12 },
		["@punctuation.special"] = { fg = colors.elixir12 },
		["@operator"] = { fg = colors.elixir12 },
		["@property"] = { fg = colors.elixir15 },
		["@field"] = { fg = colors.elixir15 },
		["@variable.member"] = { fg = colors.elixir15 },
		["@string"] = { fg = colors.elixir14 },
		["@string.regex"] = { fg = colors.elixir14 },
		["@string.escape"] = { fg = colors.elixir8 },
		["@string.special"] = { fg = colors.elixir8 },
		["@number"] = { fg = colors.elixir14 },
		["@number.float"] = { fg = colors.elixir15 },
		["@keyword"] = { fg = colors.elixir13 },
		["@keyword.module"] = { fg = colors.elixir7 },
		["@boolean"] = { fg = colors.elixir7 },
		["@keyword.function"] = { fg = colors.elixir13 },
		["@keyword.operator"] = { fg = colors.elixir12 },
		["@keyword.return"] = { fg = colors.elixir7 },
		["@keyword.conditional"] = { fg = colors.elixir7 },
		["@function"] = { fg = colors.elixir11 },
		["@function.builtin"] = { fg = colors.elixir11 },
		["@function.call"] = { fg = colors.elixir11 },
		["@function.macro"] = { fg = colors.elixir10 },
		["@method"] = { fg = colors.elixir7 },
		["@method.call"] = { fg = colors.elixir7 },
		["@variable"] = { fg = colors.elixir4 },
		["@variable.builtin"] = { fg = colors.elixir4, italic = true },
		["@variable.parameter"] = { fg = colors.elixir9 },
		["@variable.member"] = { fg = colors.elixir4 },
		["@constant"] = { fg = colors.elixir7 },
		["@constant.builtin"] = { fg = colors.elixir7 },
		["@constant.macro"] = { fg = colors.elixir10 },
		["@module"] = { fg = colors.elixir8 },
		["@type"] = { fg = colors.elixir8 },
		["@type.builtin"] = { fg = colors.elixir8, italic = true },
		["@type.definition"] = { fg = colors.elixir8 },
		["@type.qualifier"] = { fg = colors.elixir8 },
		["@tag"] = { fg = colors.elixir7 },
		["@tag.attribute"] = { fg = colors.elixir4 },
		["@tag.delimiter"] = { fg = colors.elixir9 },
	}
	return treesitter
end
return M
